#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########

set -x
set -e

rm -rf /"${BASE_BOOT_MOUNT_PATH}"/splash-screens

#cleanup
apt-get clean
apt-get autoremove -y