name: Build Raspberry Pi Image
description: Builds a raspberry pi image for the given variant

inputs:
  VARIANT:
    description: The variant to build
    required: true

outputs:
  IMAGE_NAME:
    description: The image name generated
    value: ${{ steps.image.outputs.NAME }}

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 9.7.0
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1
    - name: Generate Image Name
      id: image
      shell: bash
      run: echo "NAME=OverTheAirBrew-TapScreen-${{ matrix.variant }}-${{ steps.package-version.outputs.current-version }}" >> $GITHUB_OUTPUT
    # - uses: hoverkraft-tech/compose-action@v2.0.2
    - name: Setup docker
      shell: bash
      env:
        BASE_RELEASE_IMG_NAME: OverTheAirBrew-TapScreen-${{ matrix.variant }}-${{ steps.package-version.outputs.current-version }}
      run: |
        pnpm run setup
    - name: Build image
      shell: bash
      run: | 
        pnpm run build:${{ matrix.variant }}
