#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########

set -x
set -e

if [ "$BREW_PLATFORM_HYPERPIXEL_2_ENABLED" == "yes" ]
then
  rm -rf ./hyperpixel2r
fi