name: Build Image

on: 
  pull_request:
    types: 
      - opened
      - synchronize
  push: 
    branches: 
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - hyperpixel2r
    steps:
      - name: Checkout Project Repository
        uses: actions/checkout@v4
      - name: Build Image
        uses: ./.github/actions/build-rpi-image
        id: build-image
        with:
          VARIANT: ${{ matrix.variant }}
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: ${{ steps.build-image.outputs.IMAGE_NAME }}
          path: ./src/workspace-${{ matrix.variant }}/${{ steps.build-image.outputs.IMAGE_NAME }}.zip